### PR TITLE
correctness and performance fixes for bmap support

### PR DESCRIPTION
**Pull request by fmoessbauer**
Among others, this fixes correctness issues in the bmap writing code. For details, see the individual commit messages.

@chombourger : feel free to cherry-pick commits in case other changes need more time for discussions.

cc @bovi

### CODE REVIEW

**Comment by chombourger** [comment]
@fmoessbauer just did a quick review and this is looking very good. I really appreciate the level of details provided in the git commit logs

**Comment by fmoessbauer** [comment]
> @fmoessbauer just did a quick review and this is looking very good. I really appreciate the level of details provided in the git commit logs

That was quick. I just see that you enforce some code-style. I'll fix it and push again. We should also document this requirement in the contributing guide.

**Comment by fmoessbauer** [comment]
@chombourger please don't merge yet, I just observed another bug in the seeking part.

**Comment by fmoessbauer** [comment]
> @chombourger please don't merge yet, I just observed another bug in the seeking part.

This was a false alarm. I just tested against the code from master (which is broken). When switching to the code from this MR, everything is working correctly. Sorry for the noise.

**Pull request merged**
