### PR TITLE
mtda: add support for xz compressed images

### PR DESCRIPTION
**Pull request by vj-kumar**
Based on bz2 logic.

Closes: #121

Signed-off-by: Vijai Kumar K <Vijaikumar_Kanagarajan@mentor.com>

### CODE REVIEW

**Comment by vj-kumar** [comment]
Tested in qemu.

**Comment by chombourger** [comment]
looks good. we may need to add lzma to setup.py for this new dependency

**Comment by vj-kumar** [comment]
> looks good. we may need to add lzma to setup.py for this new dependency

It is part of the python standard library. https://docs.python.org/3/library/lzma.html

**Comment by chombourger** [comment]
> > looks good. we may need to add lzma to setup.py for this new dependency
> 
> It is part of the python standard library. https://docs.python.org/3/library/lzma.html

ah did not know. thanks for clarifying

**Pull request merged**
