### PR TITLE
images/mtda-image.inc : Add ifupdown package

### PR DESCRIPTION
**Pull request by ptsarath**
Requires the package for setting static ip
for assist board and will provide the
network/interface file.

Signed-off-by: sarath P T <Sarath_PT@mentor.com>

### CODE REVIEW

**Comment by chombourger** [comment]
Can't we do this with:
```
sudo nmcli con mod 'Wired connection 1' ipv4.addresses 192.168.1.20/24
```

**Comment by ptsarath** [comment]
@chombourger  As i dont have mtda set up at home , will visit office and let you know about the command execution.

**Comment by ptsarath** [comment]
@chombourger  i could able to set the static IP using nmcli command but few more parameters are needed to make it up like broadcastip, netmask etc. Those are not able to set by nmcli. Because of that i am not able to ping to the IP which got set it up.

**Comment by chombourger** [comment]
> @chombourger i could able to set the static IP using nmcli command but few more parameters are needed to make it up like broadcastip, netmask etc. Those are not able to set by nmcli. Because of that i am not able to ping to the IP which got set it up.

ok. that should also be possible with nmcli. I will check and share details with you

**Comment by chombourger** [comment]
```
# configure DNS
nmcli con mod 'Wired connection 1' ipv4.dns "8.8.8.8 8.8.4.4"
# configure gateway
nmcli con mod 'Wired connection 1' ipv4.gateway 192.168.1.1
# configure ip address with netmask 255.255.0.0
nmcli con mod 'Wired connection 1' ipv4.addresses 192.168.1.20/16
# configure ip address with netmask 255.255.255.0
nmcli con mod 'Wired connection 1' ipv4.addresses 192.168.1.20/24
```

**Comment by ptsarath** [comment]
@chombourger  i tried this steps too its not working yet. But i am missing  CIDR for 255.255.255.128 and setting broadcast IP too.

**Comment by chombourger** [comment]
> @chombourger i tried this steps too its not working yet. But i am missing CIDR for 255.255.255.128 and setting broadcast IP too. using nmcli

nmcli con mod 'Wired connection 1' ipv4.addresses 192.168.1.20/25 # netmask 255.255.255.128

**Comment by ptsarath** [comment]
done @chombourger . Thanks for the support.

**Comment by chombourger** [comment]
> done @chombourger . Thanks for the support.

very welcome!
feel free to add a section in the documentation to guide users also wanting to use static IP addresses

**Comment by ptsarath** [comment]
sure @chombourger

**Pull request closed without merging**
