### PR TITLE
power/qemu: configuration of qemu storage devices size via the mtda c…

### PR DESCRIPTION
**Pull request by GuBi34**
…onfiguration

Setup of the qemu DUT including the configuration of disk sizes.

Signed-off-by: Bernhard Agthe <bernhard.agthe@siemens.com>
Signed-off-by: Gunther Birk <gunther.birk@siemens.com>

### CODE REVIEW

**Comment by chombourger** [comment]
the summary line of this commit is too long
consider changing to: `power/qemu: make initial size of storage devices configurable`

**Comment by chombourger** [comment]
Happy to merge these changes if we can shorten the summary line of your commit

**Comment by GuBi34** [comment]
> the summary line of this commit is too long consider changing to: `power/qemu: make initial size of storage devices configurable`

I shortened the commit message according to your proposal

**Review by chombourger — APPROVED** [review]

**Comment by chombourger** [comment]
Note (for future PRs), you can add `Fixes: #179` before your Signed-off-by to have GitHub automatically link the PR and the issue but also close the issue when merged

**Comment by chombourger** [comment]
Example:
```
power/qemu: make initial size of storage devices configurable
Setup of the qemu DUT including the configuration of disk sizes.

Fixes: #179 
Signed-off-by: Bernhard Agthe <bernhard.agthe@siemens.com>
Signed-off-by: Gunther Birk <gunther.birk@siemens.com>
```

**Pull request merged**
