### PR TITLE
Isar update and cleanups

### PR DESCRIPTION
**Pull request by jan-kiszka**
Lifts meta-isar post bitbake 2 and resolves some historic recipe oddities.

### CODE REVIEW

**Review by chombourger — APPROVED** [review]
Looks good, thank you!

**Comment by chombourger** [comment]
reuse lint error:
The following files have no copyright and licensing information:
* meta-isar/recipes-conf/mtda-repo/files/postinst.tmpl

**Review by vj-kumar — APPROVED** [review]

**Comment by chombourger** [comment]
Latest CI build failed with:
```
2023-02-20 14:49:40 - ERROR    - Command "/build$ /work/isar/bitbake/bin/bitbake -c build mc:nanopi-neo:mtda-packages" failed
--- Error summary ---
ERROR: /build/../repo/meta-isar/recipes-core/images/mtda-image.bb: Error executing a python function in <code>:

The stack trace of python calls that resulted in this exception/failure was:
File: '<code>', lineno: 4, function: <module>
     0001:__anon_158__build____work_isar_meta_classes_base_bbclass(d)
     0002:__anon_162__build____work_isar_meta_classes_sstate_bbclass(d)
     0003:__anon_56__build____work_isar_meta_classes_image_bbclass(d)
 *** 0004:__anon_56__build____work_isar_meta_classes_sdk_bbclass(d)
     0005:__anon_21__build____work_isar_meta_classes_buildchroot_bbclass(d)
     0006:__anon_84__build____work_isar_meta_classes_imagetypes_wic_bbclass(d)
     0007:__anon_24__build____work_isar_meta_classes_imagetypes_container_bbclass(d)
     0008:__anon_305__build____work_isar_meta_classes_image_bbclass(d)
File: '/build/../work/isar/meta/classes/sdk.bbclass', lineno: 52, function: __anon_56__build____work_isar_meta_classes_sdk_bbclass
     0048:    distro_arch = d.getVar('DISTRO_ARCH')
     0049:    if mode == "0" or d.getVar('HOST_ARCH') ==  distro_arch:
     0050:        toolchain = "build-essential"
     0051:    else:
 *** 0052:        toolchain = "crossbuild-essential-" + distro_arch
     0053:    if d.getVar('ISAR_ENABLE_COMPAT_ARCH', True) == "1":
     0054:        toolchain += " crossbuild-essential-" + d.getVar('COMPAT_DISTRO_ARCH')
     0055:    d.setVar('TOOLCHAIN', toolchain)
     0056:}
Exception: TypeError: can only concatenate str (not "NoneType") to str

ERROR: Parsing halted due to errors, see error messages above
```

**Comment by jan-kiszka** [comment]
Short-term:
```
diff --git a/kas/debian/bullseye-base.yml b/kas/debian/bullseye-base.yml
index bec8a1f..3bea725 100644
--- a/kas/debian/bullseye-base.yml
+++ b/kas/debian/bullseye-base.yml
@@ -14,4 +14,5 @@ header:
   includes:
     - kas/common/base.yml
 
+#machine: qemuamd64
 distro: mtda-bullseye
```
But I will also write an Isar patch to handle the unset `DISTRO_ARCH` case which comes from an unset `MACHINE` during some parsing steps.

**Comment by jan-kiszka** [comment]
https://groups.google.com/d/msgid/isar-users/4ac8a0a6-50ac-5a76-88c0-3eef5d2f96a9%40siemens.com

**Comment by jan-kiszka** [comment]
CI should be fine now, related Isar patch was merged.

**Comment by chombourger** [comment]
> CI should be fine now, related Isar patch was merged.

It did pass. Thank you. Merging now

**Pull request merged**
