### PR TITLE
feature(www): use winbox for console & video panes

### PR DESCRIPTION
**Pull request by chombourger**

### CODE REVIEW

**Comment by chombourger** [comment]
Screenshot from 2024-01-07 12-27-46

**Comment by chombourger** [comment]
thoughts @fmoessbauer ?

**Comment by fmoessbauer** [comment]
That's much better. In the past we often had issues when using both the serial as well as the screen, as both windows overlapped (and the z-index could not be changed).

**Comment by chombourger** [comment]
Thanks.

**Pull request merged**
