### PR TITLE
Update to the latest isar

### PR DESCRIPTION
**Pull request by vj-kumar**

### CODE REVIEW

**Comment by vj-kumar** [comment]
> Not build tested. I was hoping the CI will help us.

Triggered a local build.

**Comment by vj-kumar** [comment]
> > Not build tested. I was hoping the CI will help us.
> 
> Triggered a local build.

Local build is successful for nanopi multiconfig build.

**Comment by chombourger** [comment]
> > > Not build tested. I was hoping the CI will help us.
> > 
> > 
> > Triggered a local build.
> 
> Local build is successful for nanopi multiconfig build.

Awesome, thanks!

**Review by chombourger — APPROVED** [review]
Looks good. Triggered CI checks

**Comment by jan-kiszka** [comment]
You were a bit late with setting `machine` to a valid value in your kas file, see https://github.com/siemens/jailhouse-images/commit/23574c3fef73a7074663901b85d35c0637931271.

**Comment by chombourger** [comment]
> You were a bit late with setting `machine` to a valid value in your kas file, see [siemens/jailhouse-images@23574c3](https://github.com/siemens/jailhouse-images/commit/23574c3fef73a7074663901b85d35c0637931271).

Indeed. For some reason and while you did observe this issue in jailhouse-images back in 2018,, this issue with the missing default machine setting in kas was only seen now (despite use of a not so old isar refspec)

**Pull request merged**
