### PR TITLE
Various fixes around service startup order

### PR DESCRIPTION
**Pull request by fmoessbauer**
For details, see individual commit messages. Especially have a look at the changes in p4.

cc @bovi

closes: #342

### CODE REVIEW

**Review by chombourger — APPROVED** [review]

**Comment by fmoessbauer** [comment]
Looks like there was some change in the sd notify module. I'll push a fix.

**Comment by fmoessbauer** [comment]
The package on pypi is called `systemd-python`. By that it should work with both the debian package, as well as the pypi package. @chombourger please trigger again.

**Review by chombourger — APPROVED** [review]

**Comment by fmoessbauer** [comment]
@chombourger would you mind having a look at the tox errors. It looks like we need some native dependencies on the host which cannot be downloaded with pip. If it is too complicated, we could also make this conditional (by using a try import).

**Comment by chombourger** [comment]
> @chombourger would you mind having a look at the tox errors. It looks like we need some native dependencies on the host which cannot be downloaded with pip. If it is too complicated, we could also make this conditional (by using a try import).

sure thing. I can take a look this evening

**Comment by chombourger** [comment]
> > @chombourger would you mind having a look at the tox errors. It looks like we need some native dependencies on the host which cannot be downloaded with pip. If it is too complicated, we could also make this conditional (by using a try import).
> 
> sure thing. I can take a look this evening

finally got to it. reproduced the issue locally using WSL2+ubuntu-22.04 with systemd enabled (`systemd=true` in `/etc/wsl.conf'
fixed locally and now checking with #344 

if CI tests are now passing, we could then squash my commit into relevant commit(s) from this PR

**Comment by chombourger** [comment]
Merged #344 hence closing this one.

**Pull request closed without merging**
