### PR TITLE
mtda-www: make remote assets local

### PR DESCRIPTION
**Pull request by bovi**
Some test environments don't have internet connectivity. Hence the UI should not depend on remote assets.

Signed-off-by: Daniel Bovensiepen <oss@bovi.li>

### CODE REVIEW

**Comment by bovi** [comment]
Done [here](https://github.com/siemens/mtda/pull/281/files#diff-1c645862be9de205dccc305cde10248abfe5b5a2297fc0502cbdd22cae5c9305) 

## License source information:

- `jquery.min.js`: https://github.com/jquery/jquery/commit/4f776e5ff91c48891f02d1ca3ba31132477d3972

- `socket.io.min.js`: see file

- `xterm.js`: https://github.com/xtermjs/xterm.js/blob/master/LICENSE

- `mtda/assets/material_icons.(ttf | css)`: https://github.com/google/material-design-icons/blob/master/LICENSE

**Comment by bovi** [comment]
fixed MR from https://github.com/siemens/mtda/pull/281

**Comment by chombourger** [comment]
The Apache license needs to be added to `LICENSES/` and then we should be good

**Comment by bovi** [comment]
> The Apache license needs to be added to `LICENSES/` and then we should be good

done

**Review by chombourger — APPROVED** [review]

**Comment by chombourger** [comment]
Unfortunately `reuse lint` is still complaining. This time with:
```
reuse.project - WARNING - Could not resolve SPDX License Identifier of LICENSES/Apache.txt, resolving to Apache. Make sure the license is in the license list found at <https://spdx.org/licenses/> or that it starts with 'LicenseRef-', and that it has a file extension.
```

**Comment by bovi** [comment]
@chombourger sorry I followed this guide here: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#license-short-name which is refered to by the `.reuse/dep5`. I changed the reference from `Apache` to `Apache-2.0`.

**Review by chombourger — APPROVED** [review]

**Comment by chombourger** [comment]
> @chombourger sorry I followed this guide here: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#license-short-name which is refered to by the `.reuse/dep5`. I changed the reference from `Apache` to `Apache-2.0`.

No problem at all and thank you for your fast handling of the feedback. Going to trigger a new CI check to confirm that everything is OK now (it does look OK to me).

**Comment by bovi** [comment]
I just installed `reuse`. It looks good on my machine:

Screenshot 2023-02-10 at 20 42 56

**Review by chombourger — APPROVED** [review]

**Pull request merged**
