### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by chombourger**
This is a subset of #226 (observing sporadic hangs in `_stop_composite`

### CODE REVIEW

**Comment by jan-kiszka** [comment]
Manual operation after boot-up looks fine, but auto-startup gives this again:
```
Mar 06 12:06:55 mtda systemd[1]: Started Multi-Tenant Device Access.
Mar 06 12:07:00 mtda mtda-cli[361]: Probe of the serial console failed!
Mar 06 12:07:00 mtda mtda-cli[361]: Failed to start the MTDA server!
Mar 06 12:07:00 mtda systemd[1]: mtda.service: Succeeded.
Mar 06 12:07:00 mtda systemd[1]: mtda.service: Consumed 3.660s CPU time.
```

**Comment by jan-kiszka** [comment]
..and that is #232 again. This issue cannot easily be solved generically. I'm carrying now a local version of mtda.service with the local `Wants=xxx.device` / `After=xxx.device`.

**Comment by jan-kiszka** [comment]
Auto-conf for the console looks good so far. Now testing console stability - had several crashes with the previous version today.

**Comment by chombourger** [comment]
> Verified by controlling the target
> 
> ```
>  mtda@mtda:~$ systemctl status mtda
> Warning: The unit file, source configuration file or drop-ins of mtda.service changed on disk. Run 'systemctl daemon-reload' to reload units.
> ● mtda.service - Multi-Tenant Device Access
>      Loaded: loaded (/lib/systemd/system/mtda.service; enabled; vendor preset: enabled)
>     Drop-In: /usr/lib/systemd/system/mtda.service.d
>              └─auto-dep-storage.conf
>      Active: active (running) since Mon 2022-03-21 12:59:38 UTC; 5h 16min ago
>    Main PID: 506 (mtda-cli)
>       Tasks: 6 (limit: 2289)
>      Memory: 54.6M
>         CPU: 6.282s
>      CGroup: /system.slice/mtda.service
>              └─506 /usr/bin/python3 /usr/bin/mtda-cli -d -n
> ```
> 
> The warning was observed when configuration was not changed in current power cycle.
> 
> ```
> mtda@mtda:~$ mtda-cli target on
> # debug3: main.load_timeouts_config()
> # debug3: main.load_timeouts_config: None
> # debug3: main.start()
> mtda@mtda:~$ mtda-cli target off
> # debug3: main.load_timeouts_config()
> # debug3: main.load_timeouts_config: None
> # debug3: main.start()
> ```

mtda-config.service will regenerate the auto-dep-*.conf files whenever the config is changed. this warning is consequently expected

out mtda-systemd-helper could be smarter and only update auto-dep-*.conf when they change, this however more of an optimization than anything else

**Review by vj-kumar — APPROVED** [review]

**Pull request merged**
